version: '2'

services:
  microgateway:
    build: .
    environment:
      - PORT=3001
    container_name: microgateway
    command: npm run start
    networks:
      - microgateway

  nginx:
    build: nginx
    environment:
      - GATEWAY_DNS=microgateway:3001
    ports:
      - '443:443'
    container_name: nginx
    depends_on:
      - microgateway
    networks:
      - microgateway

networks:
  microgateway:
